version: "3.8"

x-app: &default-app
  build:
    context: .
    dockerfile: Dockerfile
    target: build
    args:
      - ENV=${ENV}
  volumes:
    - .:/var/task
  restart: "unless-stopped"

services:
  api:
    <<: *default-app
    command: python manage.py runserver 0.0.0.0:9000
    env_file:
      - .env
    ports:
      - "9000:9000"
